branch-defaults:
  main:
    environment: flask-env
environment-defaults:
  flask-env:
    branch: main
    repository: origin
global:
  application_name: api
  default_ec2_keyname: aws-eb
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
